# Generated by Django 2.1 on 2019-05-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='src',
        ),
    ]
