# Generated by Django 2.1 on 2019-05-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190524_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_width',
            field=models.IntegerField(default=0),
        ),
    ]
