# Generated by Django 2.1 on 2019-05-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190524_1946'),
        ('core', '0007_fuzzysearch'),
    ]

    operations = [
    ]
