# Generated by Django 2.1 on 2019-06-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190531_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
