# Generated by Django 2.1 on 2019-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190629_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_medium',
            field=models.ImageField(editable=False, null=True, upload_to='thumbs'),
        ),
    ]
