---

- name: Ensure nginx is installed
  apt: name=nginx state=present

- name: Ensure that the deault site is enabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Copy nginx config
  template: src=nginx.j2 dest=/etc/nginx/sites-enabled/{{ application_name }}.conf

- name: Ensure nginx service is started
  service: name=nginx state=started enabled=yes
